### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by zhaoluuu** [tnagmetulla/AndroidTest#1]
Hello,Temirlan Nagmetulla~
        Excuse me, Are you a player who participated in the future skills of Kazan 2019?

**Comment by tnagmetulla** [comment]
Hello, yes!

**Comment by zhaoluuu** [comment]
Oh! I am so lucky to meet you! Because I am going to participate in the domestic mobile application development test, can you share with me some relevant information? Such as technical documents, I will thank you very much!

**Comment by tnagmetulla** [comment]
@LeedaCode pls text me via Telegram( https://t.me/tnagmetulla )
